version: "3"
services:

    www:
        image: eoponda/rpc_www
        ports: 
            - 8001:80
        volumes:
            - /home/docker/rpc/cicdpipelinedocker:/var/www 
        depends_on:
            - db
        networks:
            - frontend
        deploy:
          placement: [node.role == manager]       
          replicas: 2
          update_config:
            parallelism: 2
            
    db:
        image: eoponda/rpc_db    
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: rpc
            MYSQL_USER: rpc_user
            MYSQL_PASSWORD: userpass
            MYSQL_ROOT_PASSWORD: pass 
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - frontend
        deploy:
            placement:
             constraints: [node.role == manager]
            replicas: 2 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db:db   
        ports:
            - 8000:80
        environment:
            MYSQL_USER: rpc_user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        networks:
            - frontend
        deploy:
            replicas: 2    


networks:
  frontend:
  

volumes:
  persistent:


