version: "3"
services:

    www:
        image: eoponda/rpc_www
        ports: 
            - 8001:80
        volumes:
            - .:/var/www 
        depends_on:
            - db
        networks:
            - frontend
        deploy:
          replicas: 2
          update_config:
            parallelism: 2
          restart_policy:
            condition: on-failure    
    db:
        image: eoponda/rpc_db
        restart_policy: 
           condition: on-failure    
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: rpc
            MYSQL_USER: rpc_user
            MYSQL_PASSWORD: userpass
            MYSQL_ROOT_PASSWORD: pass 
        volumes:
            - ./database/rpc.sql:/docker-entrypoint-initdb.d/rpc.sql
            - persistent:/var/lib/mysql
        networks:
            - frontend
        deploy:
            placement:
             constraints: [node.role == manager]
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db:db
        restart_policy: 
           condition: on-failure    
        ports:
            - 8000:80
        environment:
            MYSQL_USER: rpc_user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        networks:
            - frontend


networks:
  frontend:
  

volumes:
  persistent:


