version: "2"
services:
    www:
        build:
            context: ./
            dockerfile: app.dockerfile
        ports: 
            - "8001:80"
        volumes:
            - .:/var/www
        restart: unless-stopped
        links:
            - db
        networks:
            static-network:
              ipv4_address: 192.168.1.2
    db:
        build:
            context: ./ 
            dockerfile: db.dockerfile
        restart: unless-stopped    
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: rpc
            MYSQL_USER: rpc_user
            MYSQL_PASSWORD: userpass
            MYSQL_ROOT_PASSWORD: pass 
        volumes:
            - ./database/rpc.sql:/docker-entrypoint-initdb.d/rpc.sql
            - persistent:/var/lib/mysql
        networks:
            static-network:
              ipv4_address: 192.168.1.3
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        restart: unless-stopped    
        ports:
            - 8000:80
        environment:
            MYSQL_USER: rpc_user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        networks:
            static-network:
              ipv4_address: 192.168.1.4     
volumes:
   persistent:


networks:
  static-network:
    ipam:
      config:
        - subnet: 192.168.1.0/24
         # ip_range: 172.28.5.0/24


















#   version: '3.1'
#   services:

#     # The Application
#     app:
#       build:
#         context: ./
#         dockerfile: app.dockerfile
#       volumes:
#        - ./:/var/www/html
#       restart: always
#       ports:
#         - "8080:80"    
#       depends_on:
#         - db
#       environment:
#       - "DB_PORT=3306"
#       - "DB_HOST=db"
#      # networks:
#       #  - default



#     # The Database
#     db:
#       #container_name: database
#       #image: mysql:5.4
#       image: mariadb
#       environment:
#       - MYSQL_ROOT_PASSWORD=razer123bite
#       #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
#       - MYSQL_DATABASE=razer_rpc
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=razer123bite   
#       volumes:
#         - dbdata:/var/lib/mysql
#         - ./database/rpc.sql:/docker-entrypoint-initdb.d/rpc.sql
#        # - ./my.cnf:/etc/mysql/my.cnf
#       restart: always
#       ports:
#           - "3306:3306"
#  #     networks:
#  #         - default   

#   volumes:
#     dbdata:

#  # networks :
#   #  wp-net :
#   #      driver: bridge